Add ancient fakers
etspaceman/scalacheck-faker pull request #128
Opened 2020-11-21 10:53 UTC by kkalavantavanich

## Changes Introduced

Added fakers for "ancient" module. 

## Applicable linked issues

#48 

## Checklist (check all that apply)

- [ ] This change maintains backwards compatibility
- [x] I have introduced tests for all new features and changes
- [ ] I have added documentation covering all new features and changes
- [ ] This pull-request is ready for review

2020-11-21 11:08 UTC, kkalavantavanich commented
Checking...

2020-11-21 19:58 UTC, etspaceman requested changes
Thanks for the contribution! I added some code comments above. We also need these added to the `Faker` class here: https://github.com/etspaceman/scalacheck-faker/blob/master/src/main/scala/faker/Faker.scala

2020-11-21 19:58 UTC, etspaceman commented on src/main/resources/ja/ancient.conf
> +  gods: ["アフロディテ", "アポロン", "アレス", "アルテミス", "アテナ", "デメテル", "ディオニュソス", "ハデス", "ヘパイストス", "ヘラ", "ヘルメス", "ヘスティア", "ポセイドン", "ゼウス"]
Let's be consistent with syntax and use `=` here
```suggestion
  gods = ["アフロディテ", "アポロン", "アレス", "アルテミス", "アテナ", "デメテル", "ディオニュソス", "ハデス", "ヘパイストス", "ヘラ", "ヘルメス", "ヘスティア", "ポセイドン", "ゼウス"]
```

2020-11-21 19:58 UTC, etspaceman commented on src/test/scala/faker/FakerSpec.scala
> +    testCanGen[ancient.God](locale, "ancient.God")(x => Some(x.value))
Looks good on these tests. We need another set of tests for the `Faker` class as well. See the Currency section here: https://github.com/etspaceman/scalacheck-faker/blob/master/src/test/scala/faker/FakerSpec.scala#L888

2020-11-22 12:47 UTC, etspaceman approved these changes
Thanks for the contribution!

2020-11-22 12:47 UTC, merged